### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
#      zuul网关默认整合ribbon 自动实现负载均衡轮循效果  默认30s
      serviceId: app-springcloud-member
    api-b:
        ### 以 /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: app-springcloud-order
    api-c:
        ### 以 /api-order/访问转发到订单服务
      path: /api-apy/**
      serviceId: app-springcloud-pay
